# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scale': 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale',
        'status': 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceStatus'
    }

    attribute_map = {
        'scale': 'scale',
        'status': 'status'
    }

    def __init__(self, scale=None, status=None, _configuration=None):  # noqa: E501
        """IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._scale = None
        self._status = None
        self.discriminator = None

        if scale is not None:
            self.scale = scale
        if status is not None:
            self.status = status

    @property
    def scale(self):
        """Gets the scale of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501

        scale indicates the custom resource should serve a `/scale` subresource that returns an `autoscaling/v1` Scale object.  # noqa: E501

        :return: The scale of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501
        :rtype: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale
        """
        return self._scale

    @scale.setter
    def scale(self, scale):
        """Sets the scale of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.

        scale indicates the custom resource should serve a `/scale` subresource that returns an `autoscaling/v1` Scale object.  # noqa: E501

        :param scale: The scale of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501
        :type: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale
        """

        self._scale = scale

    @property
    def status(self):
        """Gets the status of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501

        status indicates the custom resource should serve a `/status` subresource. When enabled: 1. requests to the custom resource primary endpoint ignore changes to the `status` stanza of the object. 2. requests to the custom resource `/status` subresource ignore changes to anything other than the `status` stanza of the object.  # noqa: E501

        :return: The status of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501
        :rtype: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.

        status indicates the custom resource should serve a `/status` subresource. When enabled: 1. requests to the custom resource primary endpoint ignore changes to the `status` stanza of the object. 2. requests to the custom resource `/status` subresource ignore changes to anything other than the `status` stanza of the object.  # noqa: E501

        :param status: The status of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources.  # noqa: E501
        :type: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceStatus
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources):
            return True

        return self.to_dict() != other.to_dict()
