# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiNetworkingV1IngressBackend(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource': 'IoK8sApiCoreV1TypedLocalObjectReference',
        'service': 'IoK8sApiNetworkingV1IngressServiceBackend'
    }

    attribute_map = {
        'resource': 'resource',
        'service': 'service'
    }

    def __init__(self, resource=None, service=None, _configuration=None):  # noqa: E501
        """IoK8sApiNetworkingV1IngressBackend - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._resource = None
        self._service = None
        self.discriminator = None

        if resource is not None:
            self.resource = resource
        if service is not None:
            self.service = service

    @property
    def resource(self):
        """Gets the resource of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501

        resource is an ObjectRef to another Kubernetes resource in the namespace of the Ingress object. If resource is specified, a service.Name and service.Port must not be specified. This is a mutually exclusive setting with \"Service\".  # noqa: E501

        :return: The resource of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501
        :rtype: IoK8sApiCoreV1TypedLocalObjectReference
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this IoK8sApiNetworkingV1IngressBackend.

        resource is an ObjectRef to another Kubernetes resource in the namespace of the Ingress object. If resource is specified, a service.Name and service.Port must not be specified. This is a mutually exclusive setting with \"Service\".  # noqa: E501

        :param resource: The resource of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501
        :type: IoK8sApiCoreV1TypedLocalObjectReference
        """

        self._resource = resource

    @property
    def service(self):
        """Gets the service of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501

        service references a service as a backend. This is a mutually exclusive setting with \"Resource\".  # noqa: E501

        :return: The service of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501
        :rtype: IoK8sApiNetworkingV1IngressServiceBackend
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this IoK8sApiNetworkingV1IngressBackend.

        service references a service as a backend. This is a mutually exclusive setting with \"Resource\".  # noqa: E501

        :param service: The service of this IoK8sApiNetworkingV1IngressBackend.  # noqa: E501
        :type: IoK8sApiNetworkingV1IngressServiceBackend
        """

        self._service = service

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiNetworkingV1IngressBackend, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiNetworkingV1IngressBackend):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiNetworkingV1IngressBackend):
            return True

        return self.to_dict() != other.to_dict()
