# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiCoreV1ServiceStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[IoK8sApimachineryPkgApisMetaV1Condition]',
        'load_balancer': 'IoK8sApiCoreV1LoadBalancerStatus'
    }

    attribute_map = {
        'conditions': 'conditions',
        'load_balancer': 'loadBalancer'
    }

    def __init__(self, conditions=None, load_balancer=None, _configuration=None):  # noqa: E501
        """IoK8sApiCoreV1ServiceStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._conditions = None
        self._load_balancer = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions
        if load_balancer is not None:
            self.load_balancer = load_balancer

    @property
    def conditions(self):
        """Gets the conditions of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501

        Current service state  # noqa: E501

        :return: The conditions of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501
        :rtype: list[IoK8sApimachineryPkgApisMetaV1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this IoK8sApiCoreV1ServiceStatus.

        Current service state  # noqa: E501

        :param conditions: The conditions of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501
        :type: list[IoK8sApimachineryPkgApisMetaV1Condition]
        """

        self._conditions = conditions

    @property
    def load_balancer(self):
        """Gets the load_balancer of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501

        LoadBalancer contains the current status of the load-balancer, if one is present.  # noqa: E501

        :return: The load_balancer of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501
        :rtype: IoK8sApiCoreV1LoadBalancerStatus
        """
        return self._load_balancer

    @load_balancer.setter
    def load_balancer(self, load_balancer):
        """Sets the load_balancer of this IoK8sApiCoreV1ServiceStatus.

        LoadBalancer contains the current status of the load-balancer, if one is present.  # noqa: E501

        :param load_balancer: The load_balancer of this IoK8sApiCoreV1ServiceStatus.  # noqa: E501
        :type: IoK8sApiCoreV1LoadBalancerStatus
        """

        self._load_balancer = load_balancer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiCoreV1ServiceStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiCoreV1ServiceStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiCoreV1ServiceStatus):
            return True

        return self.to_dict() != other.to_dict()
