# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'open_apiv3_schema': 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps'
    }

    attribute_map = {
        'open_apiv3_schema': 'openAPIV3Schema'
    }

    def __init__(self, open_apiv3_schema=None, _configuration=None):  # noqa: E501
        """IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._open_apiv3_schema = None
        self.discriminator = None

        if open_apiv3_schema is not None:
            self.open_apiv3_schema = open_apiv3_schema

    @property
    def open_apiv3_schema(self):
        """Gets the open_apiv3_schema of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation.  # noqa: E501

        openAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.  # noqa: E501

        :return: The open_apiv3_schema of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation.  # noqa: E501
        :rtype: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps
        """
        return self._open_apiv3_schema

    @open_apiv3_schema.setter
    def open_apiv3_schema(self, open_apiv3_schema):
        """Sets the open_apiv3_schema of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation.

        openAPIV3Schema is the OpenAPI v3 schema to use for validation and pruning.  # noqa: E501

        :param open_apiv3_schema: The open_apiv3_schema of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation.  # noqa: E501
        :type: IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps
        """

        self._open_apiv3_schema = open_apiv3_schema

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation):
            return True

        return self.to_dict() != other.to_dict()
