# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiBatchV1UncountedTerminatedPods(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'failed': 'list[str]',
        'succeeded': 'list[str]'
    }

    attribute_map = {
        'failed': 'failed',
        'succeeded': 'succeeded'
    }

    def __init__(self, failed=None, succeeded=None, _configuration=None):  # noqa: E501
        """IoK8sApiBatchV1UncountedTerminatedPods - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._failed = None
        self._succeeded = None
        self.discriminator = None

        if failed is not None:
            self.failed = failed
        if succeeded is not None:
            self.succeeded = succeeded

    @property
    def failed(self):
        """Gets the failed of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501

        failed holds UIDs of failed Pods.  # noqa: E501

        :return: The failed of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501
        :rtype: list[str]
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this IoK8sApiBatchV1UncountedTerminatedPods.

        failed holds UIDs of failed Pods.  # noqa: E501

        :param failed: The failed of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501
        :type: list[str]
        """

        self._failed = failed

    @property
    def succeeded(self):
        """Gets the succeeded of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501

        succeeded holds UIDs of succeeded Pods.  # noqa: E501

        :return: The succeeded of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501
        :rtype: list[str]
        """
        return self._succeeded

    @succeeded.setter
    def succeeded(self, succeeded):
        """Sets the succeeded of this IoK8sApiBatchV1UncountedTerminatedPods.

        succeeded holds UIDs of succeeded Pods.  # noqa: E501

        :param succeeded: The succeeded of this IoK8sApiBatchV1UncountedTerminatedPods.  # noqa: E501
        :type: list[str]
        """

        self._succeeded = succeeded

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiBatchV1UncountedTerminatedPods, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiBatchV1UncountedTerminatedPods):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiBatchV1UncountedTerminatedPods):
            return True

        return self.to_dict() != other.to_dict()
