# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'strategy': 'str',
        'webhook': 'IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion'
    }

    attribute_map = {
        'strategy': 'strategy',
        'webhook': 'webhook'
    }

    def __init__(self, strategy=None, webhook=None, _configuration=None):  # noqa: E501
        """IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._strategy = None
        self._webhook = None
        self.discriminator = None

        self.strategy = strategy
        if webhook is not None:
            self.webhook = webhook

    @property
    def strategy(self):
        """Gets the strategy of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501

        strategy specifies how custom resources are converted between versions. Allowed values are: - `\"None\"`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `\"Webhook\"`: API Server will call to an external webhook to do the conversion. Additional information   is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.  # noqa: E501

        :return: The strategy of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501
        :rtype: str
        """
        return self._strategy

    @strategy.setter
    def strategy(self, strategy):
        """Sets the strategy of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.

        strategy specifies how custom resources are converted between versions. Allowed values are: - `\"None\"`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `\"Webhook\"`: API Server will call to an external webhook to do the conversion. Additional information   is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.  # noqa: E501

        :param strategy: The strategy of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and strategy is None:
            raise ValueError("Invalid value for `strategy`, must not be `None`")  # noqa: E501

        self._strategy = strategy

    @property
    def webhook(self):
        """Gets the webhook of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501

        webhook describes how to call the conversion webhook. Required when `strategy` is set to `\"Webhook\"`.  # noqa: E501

        :return: The webhook of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501
        :rtype: IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook):
        """Sets the webhook of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.

        webhook describes how to call the conversion webhook. Required when `strategy` is set to `\"Webhook\"`.  # noqa: E501

        :param webhook: The webhook of this IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion.  # noqa: E501
        :type: IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion
        """

        self._webhook = webhook

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion):
            return True

        return self.to_dict() != other.to_dict()
