# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoTraefikV1alpha1IngressRouteUDPSpecServices(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'namespace': 'str',
        'native_lb': 'bool',
        'port': 'object',
        'weight': 'int'
    }

    attribute_map = {
        'name': 'name',
        'namespace': 'namespace',
        'native_lb': 'nativeLB',
        'port': 'port',
        'weight': 'weight'
    }

    def __init__(self, name=None, namespace=None, native_lb=None, port=None, weight=None, _configuration=None):  # noqa: E501
        """IoTraefikV1alpha1IngressRouteUDPSpecServices - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._namespace = None
        self._native_lb = None
        self._port = None
        self._weight = None
        self.discriminator = None

        self.name = name
        if namespace is not None:
            self.namespace = namespace
        if native_lb is not None:
            self.native_lb = native_lb
        self.port = port
        if weight is not None:
            self.weight = weight

    @property
    def name(self):
        """Gets the name of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501

        Name defines the name of the referenced Kubernetes Service.  # noqa: E501

        :return: The name of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this IoTraefikV1alpha1IngressRouteUDPSpecServices.

        Name defines the name of the referenced Kubernetes Service.  # noqa: E501

        :param name: The name of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def namespace(self):
        """Gets the namespace of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501

        Namespace defines the namespace of the referenced Kubernetes Service.  # noqa: E501

        :return: The namespace of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this IoTraefikV1alpha1IngressRouteUDPSpecServices.

        Namespace defines the namespace of the referenced Kubernetes Service.  # noqa: E501

        :param namespace: The namespace of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def native_lb(self):
        """Gets the native_lb of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501

        NativeLB controls, when creating the load-balancer, whether the LB's children are directly the pods IPs or if the only child is the Kubernetes Service clusterIP. The Kubernetes Service itself does load-balance to the pods. By default, NativeLB is false.  # noqa: E501

        :return: The native_lb of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :rtype: bool
        """
        return self._native_lb

    @native_lb.setter
    def native_lb(self, native_lb):
        """Sets the native_lb of this IoTraefikV1alpha1IngressRouteUDPSpecServices.

        NativeLB controls, when creating the load-balancer, whether the LB's children are directly the pods IPs or if the only child is the Kubernetes Service clusterIP. The Kubernetes Service itself does load-balance to the pods. By default, NativeLB is false.  # noqa: E501

        :param native_lb: The native_lb of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :type: bool
        """

        self._native_lb = native_lb

    @property
    def port(self):
        """Gets the port of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501

        Port defines the port of a Kubernetes Service. This can be a reference to a named port.  # noqa: E501

        :return: The port of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :rtype: object
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this IoTraefikV1alpha1IngressRouteUDPSpecServices.

        Port defines the port of a Kubernetes Service. This can be a reference to a named port.  # noqa: E501

        :param port: The port of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :type: object
        """
        if self._configuration.client_side_validation and port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def weight(self):
        """Gets the weight of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501

        Weight defines the weight used when balancing requests between multiple Kubernetes Service.  # noqa: E501

        :return: The weight of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :rtype: int
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this IoTraefikV1alpha1IngressRouteUDPSpecServices.

        Weight defines the weight used when balancing requests between multiple Kubernetes Service.  # noqa: E501

        :param weight: The weight of this IoTraefikV1alpha1IngressRouteUDPSpecServices.  # noqa: E501
        :type: int
        """

        self._weight = weight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoTraefikV1alpha1IngressRouteUDPSpecServices, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoTraefikV1alpha1IngressRouteUDPSpecServices):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoTraefikV1alpha1IngressRouteUDPSpecServices):
            return True

        return self.to_dict() != other.to_dict()
