# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip_strategy': 'IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterionIpStrategy',
        'request_header_name': 'str',
        'request_host': 'bool'
    }

    attribute_map = {
        'ip_strategy': 'ipStrategy',
        'request_header_name': 'requestHeaderName',
        'request_host': 'requestHost'
    }

    def __init__(self, ip_strategy=None, request_header_name=None, request_host=None, _configuration=None):  # noqa: E501
        """IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ip_strategy = None
        self._request_header_name = None
        self._request_host = None
        self.discriminator = None

        if ip_strategy is not None:
            self.ip_strategy = ip_strategy
        if request_header_name is not None:
            self.request_header_name = request_header_name
        if request_host is not None:
            self.request_host = request_host

    @property
    def ip_strategy(self):
        """Gets the ip_strategy of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501


        :return: The ip_strategy of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :rtype: IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterionIpStrategy
        """
        return self._ip_strategy

    @ip_strategy.setter
    def ip_strategy(self, ip_strategy):
        """Sets the ip_strategy of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.


        :param ip_strategy: The ip_strategy of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :type: IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterionIpStrategy
        """

        self._ip_strategy = ip_strategy

    @property
    def request_header_name(self):
        """Gets the request_header_name of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501

        RequestHeaderName defines the name of the header used to group incoming requests.  # noqa: E501

        :return: The request_header_name of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :rtype: str
        """
        return self._request_header_name

    @request_header_name.setter
    def request_header_name(self, request_header_name):
        """Sets the request_header_name of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.

        RequestHeaderName defines the name of the header used to group incoming requests.  # noqa: E501

        :param request_header_name: The request_header_name of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :type: str
        """

        self._request_header_name = request_header_name

    @property
    def request_host(self):
        """Gets the request_host of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501

        RequestHost defines whether to consider the request Host as the source.  # noqa: E501

        :return: The request_host of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :rtype: bool
        """
        return self._request_host

    @request_host.setter
    def request_host(self, request_host):
        """Sets the request_host of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.

        RequestHost defines whether to consider the request Host as the source.  # noqa: E501

        :param request_host: The request_host of this IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion.  # noqa: E501
        :type: bool
        """

        self._request_host = request_host

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoTraefikV1alpha1MiddlewareSpecInFlightReqSourceCriterion):
            return True

        return self.to_dict() != other.to_dict()
