# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_traefik_v1alpha1_middleware_spec_rate_limit_source_criterion import IoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion  # noqa: E501
from swagger_client.rest import ApiException


class TestIoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion(unittest.TestCase):
    """IoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion(self):
        """Test IoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_traefik_v1alpha1_middleware_spec_rate_limit_source_criterion.IoTraefikV1alpha1MiddlewareSpecRateLimitSourceCriterion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
