# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_flowcontrol_v1_flow_distinguisher_method import IoK8sApiFlowcontrolV1FlowDistinguisherMethod  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiFlowcontrolV1FlowDistinguisherMethod(unittest.TestCase):
    """IoK8sApiFlowcontrolV1FlowDistinguisherMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiFlowcontrolV1FlowDistinguisherMethod(self):
        """Test IoK8sApiFlowcontrolV1FlowDistinguisherMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_flowcontrol_v1_flow_distinguisher_method.IoK8sApiFlowcontrolV1FlowDistinguisherMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
