# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_metrics_pkg_apis_metrics_v1beta1_pod_metrics_list import IoK8sMetricsPkgApisMetricsV1beta1PodMetricsList  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sMetricsPkgApisMetricsV1beta1PodMetricsList(unittest.TestCase):
    """IoK8sMetricsPkgApisMetricsV1beta1PodMetricsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sMetricsPkgApisMetricsV1beta1PodMetricsList(self):
        """Test IoK8sMetricsPkgApisMetricsV1beta1PodMetricsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_metrics_pkg_apis_metrics_v1beta1_pod_metrics_list.IoK8sMetricsPkgApisMetricsV1beta1PodMetricsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
