# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_authentication_v1_token_review import IoK8sApiAuthenticationV1TokenReview  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiAuthenticationV1TokenReview(unittest.TestCase):
    """IoK8sApiAuthenticationV1TokenReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAuthenticationV1TokenReview(self):
        """Test IoK8sApiAuthenticationV1TokenReview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_authentication_v1_token_review.IoK8sApiAuthenticationV1TokenReview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
