# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_core_v1_seccomp_profile import IoK8sApiCoreV1SeccompProfile  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiCoreV1SeccompProfile(unittest.TestCase):
    """IoK8sApiCoreV1SeccompProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1SeccompProfile(self):
        """Test IoK8sApiCoreV1SeccompProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_core_v1_seccomp_profile.IoK8sApiCoreV1SeccompProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
