# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_cattle_k3s_v1_etcd_snapshot_file import IoCattleK3sV1ETCDSnapshotFile  # noqa: E501
from swagger_client.rest import ApiException


class TestIoCattleK3sV1ETCDSnapshotFile(unittest.TestCase):
    """IoCattleK3sV1ETCDSnapshotFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoCattleK3sV1ETCDSnapshotFile(self):
        """Test IoCattleK3sV1ETCDSnapshotFile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_cattle_k3s_v1_etcd_snapshot_file.IoCattleK3sV1ETCDSnapshotFile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
