# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_certificates_v1_certificate_signing_request import IoK8sApiCertificatesV1CertificateSigningRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiCertificatesV1CertificateSigningRequest(unittest.TestCase):
    """IoK8sApiCertificatesV1CertificateSigningRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCertificatesV1CertificateSigningRequest(self):
        """Test IoK8sApiCertificatesV1CertificateSigningRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_certificates_v1_certificate_signing_request.IoK8sApiCertificatesV1CertificateSigningRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
