# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.apiextensions_api import ApiextensionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiextensionsApi(unittest.TestCase):
    """ApiextensionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.apiextensions_api.ApiextensionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_apiextensions_api_group(self):
        """Test case for get_apiextensions_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
