# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_apps_v1_stateful_set_status import IoK8sApiAppsV1StatefulSetStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiAppsV1StatefulSetStatus(unittest.TestCase):
    """IoK8sApiAppsV1StatefulSetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAppsV1StatefulSetStatus(self):
        """Test IoK8sApiAppsV1StatefulSetStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_apps_v1_stateful_set_status.IoK8sApiAppsV1StatefulSetStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
