# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.us_containo_traefik_v1alpha1_tls_store_list import UsContainoTraefikV1alpha1TLSStoreList  # noqa: E501
from swagger_client.rest import ApiException


class TestUsContainoTraefikV1alpha1TLSStoreList(unittest.TestCase):
    """UsContainoTraefikV1alpha1TLSStoreList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsContainoTraefikV1alpha1TLSStoreList(self):
        """Test UsContainoTraefikV1alpha1TLSStoreList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.us_containo_traefik_v1alpha1_tls_store_list.UsContainoTraefikV1alpha1TLSStoreList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
