# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_api_service_list import IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList(unittest.TestCase):
    """IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList(self):
        """Test IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_kube_aggregator_pkg_apis_apiregistration_v1_api_service_list.IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
