# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_batch_v1_uncounted_terminated_pods import IoK8sApiBatchV1UncountedTerminatedPods  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiBatchV1UncountedTerminatedPods(unittest.TestCase):
    """IoK8sApiBatchV1UncountedTerminatedPods unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiBatchV1UncountedTerminatedPods(self):
        """Test IoK8sApiBatchV1UncountedTerminatedPods"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_batch_v1_uncounted_terminated_pods.IoK8sApiBatchV1UncountedTerminatedPods()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
