# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_core_v1_node_config_source import IoK8sApiCoreV1NodeConfigSource  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiCoreV1NodeConfigSource(unittest.TestCase):
    """IoK8sApiCoreV1NodeConfigSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1NodeConfigSource(self):
        """Test IoK8sApiCoreV1NodeConfigSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_core_v1_node_config_source.IoK8sApiCoreV1NodeConfigSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
