# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_core_v1_weighted_pod_affinity_term import IoK8sApiCoreV1WeightedPodAffinityTerm  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiCoreV1WeightedPodAffinityTerm(unittest.TestCase):
    """IoK8sApiCoreV1WeightedPodAffinityTerm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1WeightedPodAffinityTerm(self):
        """Test IoK8sApiCoreV1WeightedPodAffinityTerm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_core_v1_weighted_pod_affinity_term.IoK8sApiCoreV1WeightedPodAffinityTerm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
