# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_traefik_v1alpha1_middleware_spec_replace_path_regex import IoTraefikV1alpha1MiddlewareSpecReplacePathRegex  # noqa: E501
from swagger_client.rest import ApiException


class TestIoTraefikV1alpha1MiddlewareSpecReplacePathRegex(unittest.TestCase):
    """IoTraefikV1alpha1MiddlewareSpecReplacePathRegex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoTraefikV1alpha1MiddlewareSpecReplacePathRegex(self):
        """Test IoTraefikV1alpha1MiddlewareSpecReplacePathRegex"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_traefik_v1alpha1_middleware_spec_replace_path_regex.IoTraefikV1alpha1MiddlewareSpecReplacePathRegex()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
