# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_cattle_helm_v1_helm_chart import IoCattleHelmV1HelmChart  # noqa: E501
from swagger_client.rest import ApiException


class TestIoCattleHelmV1HelmChart(unittest.TestCase):
    """IoCattleHelmV1HelmChart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoCattleHelmV1HelmChart(self):
        """Test IoCattleHelmV1HelmChart"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_cattle_helm_v1_helm_chart.IoCattleHelmV1HelmChart()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
