# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.29.4+k3s1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_autoscaling_v2_horizontal_pod_autoscaler_condition import IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition(unittest.TestCase):
    """IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition(self):
        """Test IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_autoscaling_v2_horizontal_pod_autoscaler_condition.IoK8sApiAutoscalingV2HorizontalPodAutoscalerCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
